set nocompatible
syntax on
filetype indent plugin on " filetype detection[ON] plugin[ON] indent[ON]
set modeline
set t_Co=256              " enable 256-color mode
set background=dark
set tabstop=4
set shiftwidth=4
set shiftround            " always indent/outdent to the nearest tabstop
set softtabstop=4         " unify w tabstop
set expandtab
set relativenumber
set number
" Line length column at 100 char.  Taken from:
" http://superuser.com/questions/22444/make-vim-display-a-line-at-the-edge-of-the-set-textwidth
highlight OverLength ctermbg=red ctermfg=white guibg=#592929
match OverLength /\%100v.*/
set nohlsearch              " Don't continue to highlight searched phases.
set incsearch               " But do highlight as you type your search.
set ignorecase              " Make searches case-insensitive.
set nowrap                  " Don't wrap text
set list

" Status bar stuff
set laststatus=2 " Always show status bar
set statusline=%F       "tail of the filename
set statusline+=[%{strlen(&fenc)?&fenc:'none'}, "file encoding
set statusline+=%{&ff}] "file format
set statusline+=%h      "help file flag
set statusline+=%m      "modified flag
set statusline+=%r      "read only flag
set statusline+=%y      "filetype
set statusline+=%=      "left/right separator
set statusline+=%c,     "cursor column
set statusline+=%l/%L   "cursor line/total lines
set statusline+=\ %P    "percent through file

